// 定義默認值
defaultGameData = {
  playerId: '0001', // A unique identifier for the player, often generated by the system
  playerName: 'Joker',
  stats: {
      experience: 0,
      level: 1
  },
  playerHealth: 100,
  playerMana: 50,
  armor: 'Leather Armor', // A basic starting armor
  weapon: 'Wooden Sword', // A basic starting weapon
  accessories: ['Simple Ring'], // A simple starting accessory
  inventory: [
      'Health Potion', // Basic items in the player's inventory
      'Mana Potion',
      'Gold Coin (10)' // Assume the player starts with a small amount of currency
  ],
  skills: [
      'Basic Strike', // A simple attack skill
      'Block' // A basic defensive skill
  ],
  quests: [
      { id: 'qst001', name: 'Find the Lost Sheep', status: 'Not Started' }
  ],
  location: 'Starting Village',
  playTime: 0,
  achievements: [],
  settings: {
      volume: 70, // A comfortable starting volume setting
      difficulty: 'Normal', // Default difficulty setting
      language: 'en' // Default language setting
  },
  currency: {
      gold: 10, // Starting amount of gold
      gems: 0 // Premium currencies are often earned or purchased, not given at the start
  }
};

const staticData = {
  map: {
    "古林": {
      "description": "探索古老的森林",
      "objects": [
        { "name": "寶箱", "quantity": 3, "description": "在森林中可以找到寶箱。寶箱中可能包含金幣、道具或其他寶藏。" },
        { "name": "井", "quantity": 1, "description": "可以使用井來補充水分。" }
        // 可以根据实际情况继续添加其他物件
      ],
      "NPC": [
        "村莊長老",
        "旅館老闆"
        // 可以添加其他NPC
      ],
      "creatures": [
        { "name": "森林精靈", "quantity": 5 },
        { "name": "野生動物", "quantity": 12 }
        // 可以添加其他生物
      ],
      "shops": [
        { "name": "武器店"},
        { "name": "藥草店"}
        // 可以添加其他商店
      ]
    },
    "珊瑚海": {
      "description": "在這裡與海洋生物共游",
      "objects": [
        { "name": "寶箱", "quantity": 4, "description": "在海中可以找到寶箱。寶箱中可能包含金幣、道具或其他寶藏。" },
        { "name": "珊瑚", "quantity": 20, "description": "珊瑚是海洋中重要的生態系統。" }
        // 珊瑚海特有的其他物件
      ],
      "NPC": [
        "漁夫",
        "潛水教練"
        // 珊瑚海特有的其他NPC
      ],
      "creatures": [
        { "name": "海洋生物", "quantity": 30 },
        { "name": "海龍", "quantity": 2, "description": "海龍是海洋中最大的生物之一。" }
        // 珊瑚海特有的其他生物
      ],
      "shops": [
        { "name": "潛水裝備店"},
        { "name": "海產店"}
        // 珊瑚海特有的其他商店
      ]
    },
    // 更多地图...
  }
}



// 定義全域變數
let GameData = defaultGameData

//以下是主要程式碼
function Main(){
    function Start(){
      // 頁面加載時，載入遊戲進度
      loadGame();
      //請求顯示 玩家資訊 物品 技能 地圖 物件 生物 商店 NPC
    }

    // 函數從LocalStorage載入遊戲進度
    function loadGame() {
      // 嘗試從LocalStorage中獲取遊戲數據
      let gameData = JSON.parse(localStorage.getItem('gameData'));
      console.log("localStorage getItem")

      // 如果LocalStorage中沒有數據，使用默認值
      if (!gameData||gameData.playerId==null) {
          gameData = defaultGameData;
      }

      document.getElementById('player-name').textContent = gameData.playerName;
      document.getElementById('player-health').textContent = gameData.playerHealth;
      document.getElementById('player-mana').textContent = gameData.playerMana;
    }

    // 函數保存遊戲進度到LocalStorage
    function saveGameToLocal() {
      // 如果你需要将这些变量再次组合回一个对象，可以这样做：

      // 現在gameData物件會使用上面定義的變量值
      
      // 將遊戲數據保存到LocalStorage
      localStorage.setItem('gameData', JSON.stringify(gameData));
      console.log('Saving game state to local storage');
      playTime++
    }

    Start()
    saveGameToLocal()
    
    // 定時保存遊戲進度
    setInterval(saveGameToLocal, 10000); // 每5秒保存一次遊戲

    // 绑定beforeunload事件 在瀏覽器關閉時執行
    window.addEventListener('beforeunload', (event) => {
        // 在这里保存游戏状态
        saveGameToLocal()
    })
}

//對python的部分
function loadProgress() {
  fetch('http://127.0.0.1:5000/load')
  .then(response => response.json())
  .then(data => {
      console.log('Loaded progress:', data);
      // 在这里您可以根据加载的数据更新游戏状态
  })
  .catch(error => console.error('Error:', error));
}

// 示例调用
// loadProgress();

function saveProgress(progress) {
  fetch('http://127.0.0.1:5000/save', {
      method: 'POST',
      headers: {
          'Content-Type': 'application/json'
      },
      body: JSON.stringify(progress)
  })
  .then(response => response.json())
  .then(data => console.log(data))
  .catch(error => console.error('Error:', error));
}

// 示例调用
// saveProgress({ name: "玩家1", health: 80, mana: 30 });