export const defaultObjectData = [
    { id: "chest1", type: "TreasureChest", name: "寶箱", quantity: 3, description: "在森林中可以找到寶箱，可能包含金幣或寶藏。" },
    { id: "well1", type: "Well", name: "井", quantity: 1, description: "可以用來補充水分的井。" },
    { id: "mall1", type: "Building", name: "購物中心", quantity: 2, description: "現代化的購物中心，提供各種商品。" },
    { id: "snack1", type: "FoodStall", name: "街頭小吃", quantity: 1, description: "地方特色小吃，深受遊客喜愛。" },
    { id: "glacier1", type: "Landmark", name: "冰川", quantity: 1, description: "巨大的冰川，覆蓋著厚厚的冰雪。" },
    { id: "ship1", type: "Vehicle", name: "破冰船", quantity: 1, description: "用於在冰層中開路的強大船隻。" },
    { id: "ruins1", type: "Landmark", name: "古代遺跡", quantity: 1, description: "隱藏在雨林深處的古代文明遺跡。" },
    { id: "plant1", type: "Plant", name: "熱帶植物", quantity: 2, description: "繁茂且充滿生機的熱帶植物。" },
    { id: "crystal1", type: "Mineral", name: "神秘水晶", quantity: 1, description: "在洞穴深處發光的神秘水晶。" },
    { id: "hiddenChest", type: "TreasureChest", name: "隱藏的寶箱", quantity: 1, description: "藏在洞穴中的寶藏。" },
    { id: "tallGrass", type: "Plant", name: "高草", quantity: 3, description: "遍佈草原，可能藏著野生生物。" },
    { id: "ancientStone", type: "Landmark", name: "古石碑", quantity: 1, description: "刻滿神秘符文的古石碑。" },
    { id: "chest2", type: "TreasureChest", name: "寶箱", quantity: 1, description: "隱藏在海洋中的寶箱，可能藏有珍貴物品。" },
    { id: "coral1", type: "Collectible", name: "珊瑚", quantity: 2, description: "美麗且珍貴的珊瑚。" },
    { id: "ancientTreasure", type: "Treasure", name: "失落的財寶", quantity: 1, description: "傳說中的寶藏，藏於遺忘島嶼。" },
    { id: "shipwreck", type: "Landmark", name: "沉船遺骸", quantity: 1, description: "古老的沉船遺骸，可能藏著秘密。" },
    { id: "dragonEgg", type: "SpecialItem", name: "龍蛋", quantity: 1, description: "一顆尚未孵化的神秘龍蛋。" },
    { id: "mysticAltar", type: "Landmark", name: "神秘祭壇", quantity: 1, description: "傳說中的祭壇，可能蘊藏神秘力量。" },
    { id: "cursedTotem", type: "Artifact", name: "詛咒圖騰", quantity: 1, description: "散發著邪惡氣息的古老圖騰。" },
    { id: "forsakenTomb", type: "Landmark", name: "被遺忘的墓穴", quantity: 1, description: "掩藏在黑暗荒原中的古墓。" },
    { id: "tree1", type: "Landmark", name: "古樹", quantity: 1, description: "迷霧森林中的古老巨樹，高聳入雲。" },
    { id: "spring1", type: "Fountain", name: "迷霧之泉", quantity: 1, description: "清澈的泉水，常年被濃霧環繞。" }
  ];
  